# Config file for Google Cloud Build, with App Engine deployment

# Visit Cloud Build's docs page for more details and extensibility:
# https://cloud.google.com/cloud-build/docs/<language>

# Since these steps are run in sequence, a failed test results in a fail
# in the overall build, and therefore no deployment (which is good)
steps:

# Run tests
- name: 'python:3.7-stretch'
  entrypoint: 'make'
  args: ['test']

# Deploy to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
